import { createContext, useContext, useState, ReactNode } from "react";

type Language = "it" | "en";

interface DemoLanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: typeof translations.it;
}

export const translations = {
  it: {
    // DemoFlow
    demoTitle: "Demo Flusso Completo",
    demoSubtitle: "Scopri come funziona FIXO",
    phase: "Fase",
    of: "di",
    back: "Indietro",
    next: "Avanti",
    endDemo: "Fine Demo",
    demoNotice: "🎭 DEMO – dati fittizi, nessuna azione reale",
    roles: {
      cliente: "👤 Cliente",
      tecnico: "🔧 Tecnico",
      sistema: "⚡ Sistema",
      info: "ℹ️ Info",
    },
    phases: [
      { title: "Inserimento problema", description: "Caricamento foto e descrizione" },
      { title: "Diagnosi AI", description: "Analisi intelligente del problema" },
      { title: "Selezione tecnico", description: "Scelta del professionista" },
      { title: "Scelta fasce orarie", description: "Selezione disponibilità" },
      { title: "Richiesta ricevuta", description: "Vista tecnico con chat limitata" },
      { title: "Conferma appuntamento", description: "Selezione slot e sblocco contatti" },
      { title: "Tracking intervento", description: "In viaggio → In corso → Completato" },
      { title: "Intervento completato", description: "Riepilogo lavoro e costi" },
      { title: "Pagamento", description: "Pagamento dopo intervento" },
      { title: "Recensione", description: "Valutazione e commento" },
      { title: "Processo completato", description: "Riepilogo finale" },
      { title: "Come guadagna FIXO", description: "Modello ibrido e sostenibile" },
    ],
    // Phase 1
    phase1: {
      uploadTitle: "Caricamento foto del problema",
      photoUploaded: "Foto caricata: caldaia_problema.jpg",
      descriptionTitle: "Descrizione testuale libera",
      descriptionText: "La caldaia non si accende, ho provato a resettarla ma continua a mostrare un codice di errore E01. Non esce acqua calda.",
      analyzeButton: "Analizza con AI",
    },
    // Phase 2
    phase2: {
      aiDiagnosis: "Diagnosi AI",
      analysisComplete: "Analisi completata",
      problemDetected: "Problema rilevato:",
      problemType: "Guasto caldaia - Errore E01",
      possibleCauses: "Possibili cause:",
      cause1: "Problema di accensione (valvola del gas)",
      cause2: "Elettrodo di accensione danneggiato",
      cause3: "Pressostato difettoso",
      urgencyLevel: "Livello di urgenza:",
      urgencyMedium: "Media",
      estimatedCost: "Costo stimato (range indicativo):",
      recommendedSpecialty: "Tipologia tecnico consigliata:",
      technicianType: "Tecnico caldaie",
      findTechnicians: "Trova tecnici disponibili",
    },
    // Phase 3
    phase3: {
      techniciansFound: "tecnici trovati nel raggio di 10 km",
      reviews: "recensioni",
      perHour: "/ora",
      selected: "Selezionato",
      continue: "Continua",
    },
    // Phase 4
    phase4: {
      selectSlots: "Seleziona più fasce orarie",
      slotsDescription: "Puoi selezionare più opzioni. Il tecnico confermerà la sua disponibilità.",
      today: "Oggi",
      tomorrow: "Domani",
      flexible: "Sono flessibile",
      flexibleDescription: "Il tecnico può propormi altri orari",
      additionalNotes: "Note aggiuntive",
      notesPlaceholder: "Es: Citofono 'Rossi', secondo piano...",
      notesValue: "Citofono 'Bianchi', terzo piano. Il cane abbaia ma non morde.",
      summary: "Riepilogo richiesta:",
      technician: "Tecnico:",
      selectedSlots: "Fasce selezionate:",
      options: "opzioni",
      flexibility: "Flessibilità:",
      yes: "Sì",
      sendRequest: "Invia richiesta",
    },
    // Phase 5
    phase5: {
      newRequest: "Nuova richiesta di intervento!",
      receivedAgo: "Ricevuta 2 minuti fa",
      request: "Richiesta",
      pending: "In attesa",
      client: "Cliente",
      problem: "Problema:",
      estimatedDuration: "Durata stimata",
      estimatedPay: "Compenso stimato",
      proposedSlots: "Fasce orarie proposte:",
      chatWithClient: "Chat con il cliente",
      securityNotice: "I contatti e l'indirizzo saranno visibili solo dopo la conferma dell'orario.",
      chatActive: "Chat attiva. L'appuntamento non è ancora confermato.",
      clientMessage: "Buongiorno, volevo chiedere se può portare un pezzo di ricambio per la valvola?",
      technicianMessage: "Buongiorno! Porto sempre i ricambi più comuni per caldaie. Dopo aver visto il modello esatto saprò dirle se ho già il pezzo.",
      writeMessage: "Scrivi un messaggio...",
      chatLimitations: "Limitazioni chat:",
      noPhone: "Nessuna condivisione di numeri di telefono",
      noEmail: "Nessuna email",
      noExternal: "Nessun accordo esterno",
      acceptAndChoose: "Accetta e scegli orario",
      proposeOther: "Proponi altro orario",
    },
    // Phase 6
    phase6: {
      technicianSelectsSlot: "Il tecnico seleziona lo slot",
      slotSelected: "Slot selezionato",
      expectedEnd: "Fine prevista",
      appointmentConfirmed: "Appuntamento Confermato!",
      statusConfirmed: "Stato: Confermato",
      contactsUnlocked: "Contatti e indirizzo ora visibili (demo)",
      appointmentDetails: "Dettagli Appuntamento",
      confirmed: "Confermato",
      address: "Indirizzo:",
      assignedTechnician: "Tecnico Assegnato",
    },
    // Phase 7
    phase7: {
      statusTimeline: "Timeline stato intervento",
      confirmedStatus: "Confermato",
      enRoute: "In viaggio",
      departedNow: "Partito ora",
      active: "Attivo",
      inProgress: "In corso",
      waiting: "In attesa",
      completed: "Completato",
      technicianEnRoute: "Marco è in viaggio",
      estimatedTime: "Tempo stimato: 12 minuti",
      mapDemo: "Mappa demo con distanza e tempo stimato",
      distance: "Distanza:",
      simulateComplete: "Simula intervento completato",
    },
    // Phase 8
    phase8: {
      interventionCompleted: "Intervento Completato!",
      allResolved: "Tutto risolto con successo",
      workSummary: "Riepilogo lavoro svolto",
      problem: "Problema:",
      workPerformed: "Lavoro eseguito:",
      workDescription: "Sostituita valvola di sicurezza e pulito elettrodo di accensione. Verificato funzionamento completo. La caldaia ora funziona regolarmente.",
      actualDuration: "Durata effettiva:",
      completedPhotos: "Foto lavoro completato (demo):",
      costDetails: "Dettaglio costi",
      labor: "Manodopera",
      parts: "Ricambi:",
      callOut: "Uscita:",
      total: "Totale:",
      confirmCompletion: "Conferma completamento",
    },
    // Phase 9
    phase9: {
      paymentNotice: "Il pagamento avviene solo dopo il completamento del lavoro.",
      payment: "Pagamento",
      totalToPay: "Totale da pagare",
      paymentMethods: "Metodi di pagamento disponibili:",
      creditDebit: "Carta di credito / debito",
      trackedInApp: "Pagamento tracciato in app",
      paypal: "PayPal",
      cash: "Contanti",
      directToTechnician: "Pagamento diretto al tecnico",
      paymentMethodNote: "Il metodo di pagamento dipende dalle preferenze del cliente e del tecnico.",
      cashNote: "Per contanti: nessuna gestione del contante da parte di FIXO.",
      securePayment: "Pagamento sicuro e tracciato",
      paymentCompleted: "Pagamento completato (demo)",
      card: "Carta",
    },
    // Phase 10
    phase10: {
      leaveReview: "Lascia una recensione",
      technicianType: "Tecnico caldaie",
      starRating: "Valutazione a stelle",
      stars5: "5 stelle - Eccellente!",
      reviewText: "Commento testuale:",
      reviewPlaceholder: "Scrivi la tua recensione...",
      reviewValue: "Tecnico molto professionale e puntuale. Ha risolto il problema velocemente e mi ha spiegato cosa è successo. Consigliatissimo!",
      submitReview: "Invia recensione",
      reviewSent: "Recensione inviata (demo)",
    },
    // Phase 11
    phase11: {
      processCompleted: "Processo Completato!",
      fromDiagnosisToPayment: "Dalla diagnosi al pagamento, tutto tracciato e sicuro.",
      interventionCompleted: "Intervento completato",
      reviewRecorded: "Recensione registrata",
      processEnded: "Processo concluso",
      withFixoYouGot: "Con FIXO hai ottenuto:",
      verifiedTechnician: "✓ Tecnico verificato",
      transparentPrices: "✓ Prezzi trasparenti",
      trackedPayment: "✓ Pagamento tracciato",
      verifiedReview: "✓ Recensione verificata",
      discoverRevenue: "Scopri come guadagna FIXO",
    },
    // Phase 12
    phase12: {
      howFixoEarns: "Come guadagna FIXO",
      hybridModel: "Modello ibrido, semplice e trasparente",
      noAppFee: "FIXO non fa pagare l'uso dell'app",
      appFreeDescription: "FIXO mette in contatto clienti e tecnici.",
      appFree: "gratuito",
      forBoth: "L'uso dell'app è",
      noSubscription: "Nessun abbonamento, nessun costo per registrarsi.",
      twoWays: "FIXO guadagna in due modi",
      fixedCost: "Costo fisso di gestione della chiamata",
      fixedCostDesc: "Per ogni intervento confermato, FIXO applica un piccolo costo fisso di servizio.",
      aiUse: "Uso AI",
      requestManagement: "Gestione richiesta",
      alwaysVisible: "Sempre visibile",
      optionalCommission: "Commissione opzionale (2–3%)",
      optionalCommissionDesc: "Se il cliente paga tramite FIXO (carta o PayPal), la piattaforma trattiene una piccola commissione sul totale.",
      lowPercentage: "Percentuale bassa e indicata prima del pagamento.",
      paymentOutsideApp: "Pagamento fuori app",
      directToTechnician: "Pagamento diretto al tecnico",
      onlyFixedCost: "Solo costo fisso di gestione",
      noExtraCommission: "Nessuna commissione extra",
      paymentInApp: "Pagamento in app",
      trackedPayment: "Pagamento tracciato",
      clientTechProtection: "Protezione cliente e tecnico",
      supportIfProblems: "Assistenza se problemi",
      commission: "Commissione 2–3%",
      trustMessage: "FIXO guadagna solo se il servizio funziona",
      noRequestFee: "FIXO non guadagna sulla semplice richiesta.",
      earnsOnCompletion: "Guadagna solo quando l'intervento viene gestito correttamente.",
      noHiddenCosts: "Nessun costo nascosto. Nessun obbligo di pagamento in app.",
      transparentProcess: "Processo trasparente",
      clearCosts: "Costi chiari prima della conferma",
      freePayment: "Pagamento libero: in app o diretto",
      alignedInterests: "FIXO allineata all'interesse di clienti e tecnici",
      endDemoHome: "Fine demo – Torna alla home",
    },
  },
  en: {
    // DemoFlow
    demoTitle: "Complete Flow Demo",
    demoSubtitle: "Discover how FIXO works",
    phase: "Phase",
    of: "of",
    back: "Back",
    next: "Next",
    endDemo: "End Demo",
    demoNotice: "🎭 DEMO – fake data, no real actions",
    roles: {
      cliente: "👤 Customer",
      tecnico: "🔧 Technician",
      sistema: "⚡ System",
      info: "ℹ️ Info",
    },
    phases: [
      { title: "Problem Submission", description: "Photo upload and description" },
      { title: "AI Diagnosis", description: "Intelligent problem analysis" },
      { title: "Technician Selection", description: "Choose a professional" },
      { title: "Time Slot Selection", description: "Select availability" },
      { title: "Request Received", description: "Technician view with limited chat" },
      { title: "Appointment Confirmation", description: "Slot selection and contact unlock" },
      { title: "Intervention Tracking", description: "En route → In progress → Completed" },
      { title: "Intervention Completed", description: "Work and cost summary" },
      { title: "Payment", description: "Payment after intervention" },
      { title: "Review", description: "Rating and comment" },
      { title: "Process Completed", description: "Final summary" },
      { title: "How FIXO Earns", description: "Hybrid and sustainable model" },
    ],
    // Phase 1
    phase1: {
      uploadTitle: "Upload problem photo",
      photoUploaded: "Photo uploaded: boiler_problem.jpg",
      descriptionTitle: "Free text description",
      descriptionText: "The boiler won't turn on, I tried resetting it but it keeps showing error code E01. No hot water.",
      analyzeButton: "Analyze with AI",
    },
    // Phase 2
    phase2: {
      aiDiagnosis: "AI Diagnosis",
      analysisComplete: "Analysis complete",
      problemDetected: "Problem detected:",
      problemType: "Boiler failure - Error E01",
      possibleCauses: "Possible causes:",
      cause1: "Ignition problem (gas valve)",
      cause2: "Damaged ignition electrode",
      cause3: "Faulty pressure switch",
      urgencyLevel: "Urgency level:",
      urgencyMedium: "Medium",
      estimatedCost: "Estimated cost (indicative range):",
      recommendedSpecialty: "Recommended technician type:",
      technicianType: "Boiler technician",
      findTechnicians: "Find available technicians",
    },
    // Phase 3
    phase3: {
      techniciansFound: "technicians found within 10 km",
      reviews: "reviews",
      perHour: "/hour",
      selected: "Selected",
      continue: "Continue",
    },
    // Phase 4
    phase4: {
      selectSlots: "Select multiple time slots",
      slotsDescription: "You can select multiple options. The technician will confirm availability.",
      today: "Today",
      tomorrow: "Tomorrow",
      flexible: "I'm flexible",
      flexibleDescription: "The technician can propose other times",
      additionalNotes: "Additional notes",
      notesPlaceholder: "E.g.: Intercom 'Smith', second floor...",
      notesValue: "Intercom 'White', third floor. The dog barks but doesn't bite.",
      summary: "Request summary:",
      technician: "Technician:",
      selectedSlots: "Selected slots:",
      options: "options",
      flexibility: "Flexibility:",
      yes: "Yes",
      sendRequest: "Send request",
    },
    // Phase 5
    phase5: {
      newRequest: "New intervention request!",
      receivedAgo: "Received 2 minutes ago",
      request: "Request",
      pending: "Pending",
      client: "Customer",
      problem: "Problem:",
      estimatedDuration: "Estimated duration",
      estimatedPay: "Estimated pay",
      proposedSlots: "Proposed time slots:",
      chatWithClient: "Chat with customer",
      securityNotice: "Contacts and address will be visible only after time confirmation.",
      chatActive: "Chat active. Appointment not yet confirmed.",
      clientMessage: "Hello, I wanted to ask if you can bring a spare part for the valve?",
      technicianMessage: "Hello! I always carry the most common boiler spare parts. After seeing the exact model I'll know if I have the part.",
      writeMessage: "Write a message...",
      chatLimitations: "Chat limitations:",
      noPhone: "No phone number sharing",
      noEmail: "No email",
      noExternal: "No external agreements",
      acceptAndChoose: "Accept and choose time",
      proposeOther: "Propose other time",
    },
    // Phase 6
    phase6: {
      technicianSelectsSlot: "Technician selects slot",
      slotSelected: "Slot selected",
      expectedEnd: "Expected end",
      appointmentConfirmed: "Appointment Confirmed!",
      statusConfirmed: "Status: Confirmed",
      contactsUnlocked: "Contacts and address now visible (demo)",
      appointmentDetails: "Appointment Details",
      confirmed: "Confirmed",
      address: "Address:",
      assignedTechnician: "Assigned Technician",
    },
    // Phase 7
    phase7: {
      statusTimeline: "Intervention status timeline",
      confirmedStatus: "Confirmed",
      enRoute: "En route",
      departedNow: "Just departed",
      active: "Active",
      inProgress: "In progress",
      waiting: "Waiting",
      completed: "Completed",
      technicianEnRoute: "Marco is on the way",
      estimatedTime: "Estimated time: 12 minutes",
      mapDemo: "Demo map with distance and estimated time",
      distance: "Distance:",
      simulateComplete: "Simulate completed intervention",
    },
    // Phase 8
    phase8: {
      interventionCompleted: "Intervention Completed!",
      allResolved: "All successfully resolved",
      workSummary: "Work summary",
      problem: "Problem:",
      workPerformed: "Work performed:",
      workDescription: "Replaced safety valve and cleaned ignition electrode. Verified complete operation. The boiler now works properly.",
      actualDuration: "Actual duration:",
      completedPhotos: "Completed work photos (demo):",
      costDetails: "Cost details",
      labor: "Labor",
      parts: "Parts:",
      callOut: "Call-out:",
      total: "Total:",
      confirmCompletion: "Confirm completion",
    },
    // Phase 9
    phase9: {
      paymentNotice: "Payment occurs only after work completion.",
      payment: "Payment",
      totalToPay: "Total to pay",
      paymentMethods: "Available payment methods:",
      creditDebit: "Credit / debit card",
      trackedInApp: "Payment tracked in app",
      paypal: "PayPal",
      cash: "Cash",
      directToTechnician: "Direct payment to technician",
      paymentMethodNote: "Payment method depends on customer and technician preferences.",
      cashNote: "For cash: no cash handling by FIXO.",
      securePayment: "Secure and tracked payment",
      paymentCompleted: "Payment completed (demo)",
      card: "Card",
    },
    // Phase 10
    phase10: {
      leaveReview: "Leave a review",
      technicianType: "Boiler technician",
      starRating: "Star rating",
      stars5: "5 stars - Excellent!",
      reviewText: "Written review:",
      reviewPlaceholder: "Write your review...",
      reviewValue: "Very professional and punctual technician. Solved the problem quickly and explained what happened. Highly recommended!",
      submitReview: "Submit review",
      reviewSent: "Review sent (demo)",
    },
    // Phase 11
    phase11: {
      processCompleted: "Process Completed!",
      fromDiagnosisToPayment: "From diagnosis to payment, all tracked and secure.",
      interventionCompleted: "Intervention completed",
      reviewRecorded: "Review recorded",
      processEnded: "Process ended",
      withFixoYouGot: "With FIXO you got:",
      verifiedTechnician: "✓ Verified technician",
      transparentPrices: "✓ Transparent prices",
      trackedPayment: "✓ Tracked payment",
      verifiedReview: "✓ Verified review",
      discoverRevenue: "Discover how FIXO earns",
    },
    // Phase 12
    phase12: {
      howFixoEarns: "How FIXO Earns",
      hybridModel: "Hybrid, simple and transparent model",
      noAppFee: "FIXO doesn't charge for app usage",
      appFreeDescription: "FIXO connects customers and technicians.",
      appFree: "free",
      forBoth: "App usage is",
      noSubscription: "No subscription, no registration cost.",
      twoWays: "FIXO earns in two ways",
      fixedCost: "Fixed call management cost",
      fixedCostDesc: "For each confirmed intervention, FIXO applies a small fixed service cost.",
      aiUse: "AI Usage",
      requestManagement: "Request management",
      alwaysVisible: "Always visible",
      optionalCommission: "Optional commission (2–3%)",
      optionalCommissionDesc: "If the customer pays via FIXO (card or PayPal), the platform retains a small commission on the total.",
      lowPercentage: "Low percentage, shown before payment.",
      paymentOutsideApp: "Payment outside app",
      directToTechnician: "Direct payment to technician",
      onlyFixedCost: "Only fixed management cost",
      noExtraCommission: "No extra commission",
      paymentInApp: "In-app payment",
      trackedPayment: "Tracked payment",
      clientTechProtection: "Customer and technician protection",
      supportIfProblems: "Support if problems",
      commission: "2–3% commission",
      trustMessage: "FIXO earns only if the service works",
      noRequestFee: "FIXO doesn't earn on simple requests.",
      earnsOnCompletion: "Earns only when the intervention is properly managed.",
      noHiddenCosts: "No hidden costs. No obligation to pay in-app.",
      transparentProcess: "Transparent process",
      clearCosts: "Clear costs before confirmation",
      freePayment: "Free payment choice: in-app or direct",
      alignedInterests: "FIXO aligned with customer and technician interests",
      endDemoHome: "End demo – Back to home",
    },
  },
};

const DemoLanguageContext = createContext<DemoLanguageContextType | null>(null);

export function DemoLanguageProvider({ children, initialLang = "it" }: { children: ReactNode; initialLang?: Language }) {
  const [lang, setLang] = useState<Language>(initialLang);
  const t = translations[lang];

  return (
    <DemoLanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </DemoLanguageContext.Provider>
  );
}

export function useDemoLanguage() {
  const context = useContext(DemoLanguageContext);
  if (!context) {
    throw new Error("useDemoLanguage must be used within a DemoLanguageProvider");
  }
  return context;
}
